# requiring the environment of Ruby 2.3.x
image: ruby:2.5.1
# add bundle cache to 'vendor' for speeding up builds
cache:
  paths:
   - vendor/
before_script:
         - gem update --system && gem install bundler && bundle config set path 'vendor' && bundler update --bundler && bundle install
# the 'pages' job will deploy and build your site to the 'public' path
pages:
  stage: deploy
  script:
   - bundle exec jekyll build -d public/
  artifacts:
     paths:
       - public
  only:
   - master # this job will affect only the 'master' branch